### ISSUE TITLE
[NEW FEATURE] Micro-Meta App / Explorer integration

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-Electron#48]
First Window

![image](https://user-images.githubusercontent.com/4050585/231283370-c252913e-f726-42d3-b4c9-c42e86954a1d.png)

- [ ] Insert tooltips for the two buttons (use available Tooltip template)
- [ ] Change name of buttons to: Micro-Meta App  and Micro-Meta Explorer
- [ ] Add TBD text to go under the main name

**Comment by strambc** [comment]
Third Screen (Compare - Viewer Component)

![image](https://user-images.githubusercontent.com/4050585/231288013-3d485ae9-7349-480d-b686-8bcdf68e9028.png)

- [ ] Add separation vertical separation line between different microscopes
