### ISSUE TITLE
[NEW FEATURE] Micro-Meta App / Explorer integration

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-Electron#50]
First Window

![image](https://user-images.githubusercontent.com/4050585/231283370-c252913e-f726-42d3-b4c9-c42e86954a1d.png)

- [x] Change name of buttons to: Micro-Meta App  and Micro-Meta Explorer
- [x] Insert tooltips for the two buttons (use available Tooltip template)
- [x] Add TBD text to go under the main name (similar to what is present in Micro-Meta App)

**Micro-Meta Explorer**
Button Main Title --> Micro-Meta Explorer
Button Sub Title --> Compare the hardware components of different available microscopes and select the one you are interested in."
Tooltip title --> "Micro-Meta Explorer"
Tooltip body --> "Click this button to launch Micro-Meta Explorer."

=======
**Micro-Meta App button** 
Button Main Title --> Micro-Meta App
Button Sub Title --> Collect information about the microscope hardware components and the image acquisition settings associated with specific datasets.
Tooltip title --> "Micro-Meta App"
Tooltip body --> "Click this button to launch Micro-Meta App."

- [ ] Define Logos for buttons (same as Favicons for the two components)
- [ ] Redefine Micro-Meta App logo to make it more generic.

**Comment by strambc** [comment]
Second Screen (Explorer)

![image](https://user-images.githubusercontent.com/4050585/231284223-c74df2e1-2e8a-4ef4-bd31-967d044bacb1.png)

- [x] Define order of top right buttons search list 

-- NEW ORDER: search field / search button / clear search / help / about 

- [x] Update the "About" content for Micro-Meta App --> VERSION HAS TO BE KEPT UP TO DATE

"Micro Meta App is an open-source, community-defined, and easy-to-use software platform that provides an intuitive visual guide to capturing and managing Microscopy Metadata based on the [4DN-BINA-QUAREP extension](https://github.com/WU-BIMAC/NBOMicroscopyMetadataSpecs/tree/master/Model/stable%20version/v02-01) of the [OME data model](https://docs.openmicroscopy.org/ome-model/6.1.1/developers/model-overview.html) .

App version: **UPDATE VERSION**
Model version: 2.01.1

(c) Copyright 2018-2023 University of Massachusetts Chan Medical School. All Rights Reserved.
The software is distributed under the terms of the [GNU General Public License v3.0.](https://www.gnu.org/licenses/gpl-3.0.html)"

- [x] Define the "About" content for Micro-Meta Explorer --> VERSION HAS TO BE KEPT UP TO DATE

"Micro-Meta Explorer is an open-source, community-defined, and easy-to-use software platform that provides an intuitive visual guide for exploring and comparing the hardware configuration of available microscopes based on the [4DN-BINA-QUAREP extension](https://github.com/WU-BIMAC/NBOMicroscopyMetadataSpecs/tree/master/Model/stable%20version/v02-01) of the [OME data model](https://docs.openmicroscopy.org/ome-model/6.1.1/developers/model-overview.html) .

App version: **UPDATE VERSION**
Model version: 2.01.1

(c) Copyright 2018-2023 University of Massachusetts Chan Medical School. All Rights Reserved.
The software is distributed under the terms of the [GNU General Public License v3.0.](https://www.gnu.org/licenses/gpl-3.0.html)"

- [ ] Define icons for search, clear search
- [x] Define the tooltip for search field, search button, clear search button

**Search button tooltip:**
 -- TITLE: "Search"
 -- BODY: "Click here to launch a search for microscope components"

**Clear button tooltip:**
 -- TITLE: "Clear search field"
 -- BODY: "Click here to clear the search field and start a new search"

- [x] Rename "Parent Home" button 
-- "Home" button returns to the Home screen of each individual component
-- The "Parent Home" button returns to the screen in which the selection is done between components
Change name from  "Parent Home" to > Component Selector

**Comment by Akramhar** [comment]
all done except for logos / favicon
